### ISSUE TITLE
Error message occured in common.js file

### ISSUE THREAD

**Issue by SasithaGamage** [google-marketing-solutions/vigenair#11]
I got the below two errors, Could you help me to fix .

1. Deprecation Warning and Missing Refresh Token:
(node:92853) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Error retrieving access token: Error: No refresh token or refresh handler callback is set.

2. TypeError: Cannot read properties of undefined (reading 'match'):
/home/sasithagamage/vigenair/dist/common.js:143
        let webAppLink = lastNonEmptyLine.match(/- (.*) @.*/);
                                          ^

TypeError: Cannot read properties of undefined (reading 'match')
    at UiDeploymentHandler.deployUi (/home/sasithagamage/vigenair/dist/common.js:143:43)
    at /home/sasithagamage/vigenair/dist/index.js:87:41
    at Generator.next (<anonymous>)
    at fulfilled (/home/sasithagamage/vigenair/dist/index.js:20:58)

![Screenshot 2024-07-31 100023](https://github.com/user-attachments/assets/407f0096-681a-41f5-a8d2-94cbccc6739c)

**Comment by SasithaGamage** [comment]
I have updated the .clasp.json file with the following values

{
  "token": {
    "access_token": "your-new-access-token",
    "refresh_token": "your-new-refresh-token",
    "scope": "https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/cloud-platform",
    "token_type": "Bearer",
    "expiry_date": 1629186341  // Use the calculated expiry date
  },
  "oauth2ClientSettings": {
    "clientId": "your-client-id",
    "clientSecret": "your-client-secret",
    "redirectUri": "urn:ietf:wg:oauth:2.0:oob"
  },
  "isLocalCreds": true
}

**Comment by mohabfekry** [comment]
There are several unnecessary scopes in there, and you shouldn't need to manually update your .clasp.json file.

Could you please share your node and npm versions?
Mine are node: v18.19.1 and npm: 10.2.4, and with those versions the issue is not reproducible.

The second "match" problem is a side-effect of the first, because your Apps Script project wasn't created or deployed, and so we couldn't "extract" the deployed Web App URL from the npm logs.

If you're going to upgrade node and npm please make sure to `git reset --hard` your workspace before rerunning `npm start`, and make sure you clean up any `.*clasp*.json` files in `<root>/dist/`, `<root>/ui/dist/` and `<root>/ui/` before your run `npm start`.

**Comment by SasithaGamage** [comment]
Okay Thanks, My node version and npm version are v22.5.1, 10.8.2
