### ISSUE TITLE
UI isn't loading. App is blocked after Oauth screen

### ISSUE THREAD

**Issue by gazly** [google-marketing-solutions/vigenair#12]
Getting the below error when I tried to log in to the application. 

<img width="866" alt="image" src="https://github.com/user-attachments/assets/1841bcc3-1fa0-4207-a90a-08e58521d4f0">

Following are screenshots from the terminal, did I make any mistakes? Should I configure the Oauth Consent screen? 

<img width="887" alt="image" src="https://github.com/user-attachments/assets/84a521de-6844-40e8-930c-6207a16c1182">
<img width="810" alt="image" src="https://github.com/user-attachments/assets/60bc17e6-6bac-44f7-bd09-78047fa8d0b7">

**Comment by mohabfekry** [comment]
Thanks for the screenshots. It looks like you UI deployment completely successfully but your Cloud Components didn't - this is expected for **newly created** projects as mentioned on the README (see the "Note" in https://github.com/google-marketing-solutions/vigenair#get-started) and you'd just need to wait for up to 7 minutes until the Eventarc Service Agent is created and provisioned. If you retry the deployment now (just for Cloud, you don't need to redeploy the UI since it completed successfully) it should work.

Now this, however, will not fix the "This app is blocked" issue. I suspect you're using a Workspace account (not a private gmail one) and I believe your organization's policies might be restricting access to scripts from Cloud projects that do not reside in your workspace organization. This is a very common Apps Script problem. This is because Apps Script, by default, uses auto-generated Cloud projects for authentication (called "Default" Cloud projects) and you'll need to change it to use your organization's Cloud project (the one that starts with v***** as shown above in the screenshots) instead as follows:
1. Configure the OAuth consent screen on your organization project (v****)
2. Navigate to the Dashboard of your Cloud project (https://console.cloud.google.com/home/dashboard?project=<your-project> and copy the numerical "Project number".
3. Switch the script project to use your configured Cloud project instead of the "Default" one by entering the numerical Project number in the script settings dialog. You can find more information about this in https://developers.google.com/apps-script/guides/cloud-platform-projects#standard

**Comment by gazly** [comment]
Thank you based on your suggestions and after OAuth configurations application is loading via Appscript 

But the site is stuck here-- tried with many videos 

Content language is not English, is it a concern? 

<img width="1701" alt="image" src="https://github.com/user-attachments/assets/4f33837c-78dd-47a1-8af0-0a21429f30d4">

I checked the bucket, file is available there 

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/65d84ea3-15b6-4b39-b261-319f0ebfd081">
