### ISSUE TITLE
No sign of vigenair bucket/cloud function

### ISSUE THREAD

**Issue by 202103817** [google-marketing-solutions/vigenair#22]
I have run the npm start command, enabling cloud functions and without deploying the UI.

The script runs succesfully, however when I go to the GCP project I see no sign of the vigenair bucket. Same goes for the cloud function, and I don't understand why.

I have the following permissions on my account:

1.	Storage Admin
2.	Cloud Function Developer
3.	Vertex AI User

FYI when I run the script I get the following warning. Is this the reason no bucket/function seems to have been created?

_WARNING:
Cannot add the project "my-project" to ADC as the quota project because the account in ADC does not have the "serviceusage.services.use" permission on this project. You might receive a "quota_exceeded" or "API not enabled" error. Run $ gcloud auth application-default set-quota-project to add a quota project._

**Comment by mohabfekry** [comment]
If the script terminates successfully quickly that means the cloud function didn't get deployed, probably due to the ADC error you saw above. Based on the requirements defined here: https://github.com/google-marketing-solutions/vigenair?tab=readme-ov-file#requirements you also need to have the `Project IAM Admin` role to be able to run the commands that set up roles and policy bindings in the deployment script. Please try to get access to that role before deploying.
